### ISSUE TITLE
linker command failed with exit code 1

### ISSUE THREAD

**Issue by JavoByte** [CORBmx/react-native-openpay#1]
I see this library isn't updated to latest react native version. Perhaps this is the issue. I'm using react native version `0.45` Any chances fixing this?
```
ld: '/Users/Javier/Library/Developer/Xcode/DerivedData/LaxApp-ffnuyprwdkwnvacuxnfagyzacyej/Build/Products/Debug-iphoneos/libRNOpenpay.a(DataCollection.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/Javier/Library/Developer/Xcode/DerivedData/LaxApp-ffnuyprwdkwnvacuxnfagyzacyej/Build/Products/Debug-iphoneos/libRNOpenpay.a' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by CesarLanderos** [comment]
i could do it but RN i don't have any project to test it against or something, but i am really open to seeing a PR from someone adding support for the latest version of react-native 😬 .

**Comment by CesarLanderos** [comment]
this issue have been inactive for a couple of months, so i'm going to close it, we can re-open it if somebody else has the same issue or creates a fix.

**Comment by luispeerez** [comment]
also having problems with this, using xcode 10, react native 0.55.4

**Comment by CesarLanderos** [comment]
Unfurtunately I don’t have any setup to tests this 😓

If anyone can find a way to fix this it would be very appreciated 🙏

It might be a matter of updating the sdk, hopefully

**Comment by luispeerez** [comment]
Here is the solution, it worked for me, consists in setting the Property "Enable Bitcode" to NO in Build Settings https://stackoverflow.com/a/30856364
