### ISSUE TITLE
Unhandled JS Exception: TypeError: null is not an object

### ISSUE THREAD

**Issue by cesar-alamilla** [CORBmx/react-native-openpay#12]
Hola que tal! 

Acabo de instalar tu librería y al intentar iniciar el proyecto me encuentro con el siguiente problema: 

![image](https://user-images.githubusercontent.com/12970779/83656135-cd7cdd80-a584-11ea-9e4d-d5461a723188.png)

Sospecho que quizá el subir de versión de RN afectó la forma en que se vinculan los NativeModules, pues si modifico el archivo index.js y para la asignación de los métodos nativos uso arrow function me deja iniciar el proyecto sin embargo sigo sin poder acceder a las funciones de tu librería.

**Comment by cesar-alamilla** [comment]
Despues de varios días de revisar el problema me pude percatar que el problema era que no se estaba cargando los archivos fuente en el archivo podspec esto debido a que intenta cargarlos de la siguiente forma:

` s.source_files  = "apple/**/*.{h,m}"`

sin embargo no existe una carperta llamada apple que contenga los archivos fuente para iOS, por lo que debería quedar de la siguiente forma

`s.source_files  = "RNOpenpay/**/*.{h,m}"`

sin embargo al realizar esto, vuelvo a instalar el pod y al iniciar el proyecto me encuentro con el siguiente error 

![image](https://user-images.githubusercontent.com/12970779/83960528-4020de00-a84f-11ea-9229-301d13019c03.png)

Por lo que he investigado este error va relacionado a que no se pueden vincular los encabezados (.h) con el objeto que lo quiere utilizar, el archivo "openpay.a" he buscado en internet como solventar este problema pero no he tenido suerte, espero alguien me pueda ayudar a resolver este problema

**Comment by CesarLanderos** [comment]
@MarcoMacedoP tienes idea de cual puede ser el problema?

**Comment by jagowm** [comment]
Mismo problema por aqui... alguna actualización???

**Comment by davidcort** [comment]
Same problem :(

 "react": "16.13.1",
 "react-native": "0.63.1"

**Comment by cesar-alamilla** [comment]
@davidcort , @GuillermoGuevara 

Seguí investigando un poco más y creo que el problema es con las librerías de Openpay para iOS que a la fecha original de la publicación estaban ya algo viejas (actualmente no he revisado si continúan así) ya no seguí investigando pues la verdad es que se muy poco de Objective C. 

Por otro lado encontré una solución un tanto sencilla, el proyecto "oficial" de Openpay para React Native el unico problema que tiene es con el uso de dependencias de terceros que estan desactualizadas para las ultimas versiones de RN, sin embargo la lógica para la obtención del device session id y del token de openpay sigue completamente funcional.
Al final fue lo que terminé haciendo, crear un componente que use esa lógica para poder procesar los datos de la tarjeta. 

Veré si en los próximos días puedo generar un componente más genérico y poderlo subir a un repositorio mientras tanto pueden revisar la implementación en puro JS no es compleja. 

Saludos!

**Comment by davidcort** [comment]
> @davidcort , @GuillermoGuevara
> 
> Seguí investigando un poco más y creo que el problema es con las librerías de Openpay para iOS que a la fecha original de la publicación estaban ya algo viejas (actualmente no he revisado si continúan así) ya no seguí investigando pues la verdad es que se muy poco de Objective C.
> 
> Por otro lado encontré una solución un tanto sencilla, el proyecto "oficial" de Openpay para React Native el unico problema que tiene es con el uso de dependencias de terceros que estan desactualizadas para las ultimas versiones de RN, sin embargo la lógica para la obtención del device session id y del token de openpay sigue completamente funcional.
> Al final fue lo que terminé haciendo, crear un componente que use esa lógica para poder procesar los datos de la tarjeta.
> 
> Veré si en los próximos días puedo generar un componente más genérico y poderlo subir a un repositorio mientras tanto pueden revisar la implementación en puro JS no es compleja.
> 
> Saludos!

Thanks, i will stay in tune :)

**Comment by erie-e9** [comment]
Obtengo el mismo error, me han dicho que Apple te obliga a usar su medio de pago, pero necesito usar sí o sí este paquete. ¿Alguien pudo resolverlo?

**Comment by CesarLanderos** [comment]
Esta librería contiene código que las app stores no aceptan, y por razones expuestas en el siguiente link, no se seguira manteniendo, les recomiendo seguir las recomendaciones en ese mismo hilo

https://github.com/CORBmx/react-native-openpay/issues/13#issuecomment-670982323
