### ISSUE TITLE
 Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability 

### ISSUE THREAD

**Issue by ferAgredano** [CORBmx/react-native-openpay#13]
I'm using react-native-openpay on my project and tried to upload it into apple connect, I received an email with this issue: "ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability".
I searched on the node_modules folder with the command "grep UIWebView -r node_modules" and I got this output:
"node_modules/react-native-openpay/RNOpenpay/DeviceCollectorSDK.h:@interface DeviceCollectorSDK : NSObject
Binary file node_modules/react-native-openpay/RNOpenpay/openpay.a matches"
https://developer.apple.com/documentation/webkit/wkwebview/
I've tried replacing UIWebViewDelegate with WKUIDelegate on the DeviceCollectorSDK.h but seems that the openpay.a binary file still matches with UIWebView.
How can I generate again the openpay.a file? I'm really new with the IOS compilation.
And this is really what is not allowing me to upload to apple connect?

RN: 0.6
react-native-openpay: ^2.0.1
I'm using cocoapods but the library is linked manually because y haven't found how to add it with pods.

Thanks, and regards!

**Comment by CesarLanderos** [comment]
Hi @ferAgredano ! thanks for the report, i think we can just take the latest release of the binaries from the openpay repositories:

https://github.com/open-pay/openpay-ios

hopefully the last version will have the UIWebView already replaced, if not, we can do a harder migration using the more recent swift implementation, although it may require significantly more work

**Comment by CesarLanderos** [comment]
could you help me with that? 🙏 i have no way to testing that right now

**Comment by ferAgredano** [comment]
Hi Cesas, thanks for the reply.
I already tried, but the last release still uses the UIWebView component.
So we contacted the openpay support and they told us they are aware of
this issue and working on it.
Once they release the new version I could try to replace the binaries and
notify you if it works.
Regards!

**Comment by ferAgredano** [comment]
Hi Cesar, I was checking and seems that the v2 of the open pay (objective-c) library has not the DeviceCollectorSDK which is the one who has UIWebViewDelegate.
[https://github.com/open-pay/openpay-ios/tree/master/v2](https://github.com/open-pay/openpay-ios/tree/master/v2)
I want to try replacing the binaries but the new version seems to have some differences on the structure and I don't know which files to replace.
I also have tried to replace the line @interface DeviceCollectorSDK : NSObject <UIWebViewDelegate> on DeviceCollectorSDK.h but the openpay.a file still has the UIWebView and I don't know how to edit that file.
Could you guide me with that process?
Regards!

**Comment by ferAgredano** [comment]
Hi Cesar some update, the openpay develop team told us that the objective-c library is already deprecated, they told us that we need to use te swift library [https://github.com/open-pay/openpay-swift-ios](https://github.com/open-pay/openpay-swift-ios).
How can we proceede with this new situation?

**Comment by CesarLanderos** [comment]
Hey @ferAgredano! thanks for coming back with an answer!, i can begin the swift transition! the only thing is that i may need your help later to test the changes, since i don't have a development environment that can make requests to openpay.

**Comment by ferAgredano** [comment]
@CesarLanderos  of course, let me know when you need to test.
Thanks a lot!

**Comment by CesarLanderos** [comment]
@ferAgredano I spent some time on this migration, and I just realized that the swift version now has to display a form, I need to figure out how to do that in a RN project, but, to be honest, this would make this library no different from the one Openpay now has:

https://github.com/open-pay/openpay-react-native/blob/master/index.js

I may do the change, just for the sake of learning how to do it with the current constraints, but I would advise to instead "copy and paste" the code from the link above (even the session id is just a uuid, i thought it was something more complex, but it makes sense), it seems to do all what the native sdks do but fully with javascript.

TBH i don't know when will I continue with the migration, hope this is useful for you!
