### ISSUE TITLE
undefined is not an object 

### ISSUE THREAD

**Issue by ghost** [CORBmx/react-native-openpay#2]
i got this error when i try to use this library

` async createCard()
    {
        openpay.setup('xxxxxxxxxx', 'sk_xxxxxxxxxxxxxxxxx');
        openpay.createCardToken({
            holder_name: 'John Doe',
            card_number: '4111111111111111',
            expiration_month: '02',
            expiration_year: '20',
            cvv2: '110'
        })
            .then(token => console.log(token));
    }
`

![screen shot 2017-09-29 at 3 24 51 pm](https://user-images.githubusercontent.com/10695637/31034629-79bc7474-a52a-11e7-8fcc-b2450b8954a5.png)

**Comment by CesarLanderos** [comment]
seems like the `react-native link` command didn't do what it was supposed to do, did it made any change at  all in your project?

**Comment by ghost** [comment]
yup, it made the changes on xcode project, im using expo detached project and the latest version of RN

**Comment by Diego-Fu** [comment]
Hi! i had to modify the next file:

` /node_modules/react-native-openpay/android/src/main/java/com/RNOpenpay/RNOpenpayPackage.java`

just delete the next lines

```
@Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }
```

Hope this can help you.

**Comment by ghost** [comment]
habrá alguna forma de implementar esto sin tener que usar código nativo ? me refiero a usar expo (expo.io) el cual solo requiere JS

**Comment by Diego-Fu** [comment]
Expo por el momento no soporta esta librería, justo ahora estoy en un proyecto con openpay y tuve que hacer eject para usar esta librería, ese fue mi forma de arreglarlo por el momento.

**Comment by ghost** [comment]
yo lo estoy haciendo por medio de el api y me funciona bien pero estoy viendo la opción de portarlo como paquete para que los demás lo puedan usar sin necesidad de tener que ejectar...

**Comment by Diego-Fu** [comment]
Eso estaría increíble, si necesitas ayuda cuenta conmigo!

**Comment by madaviela** [comment]
pues me vendría bien algo de ayuda por que aun tengo algo de dudas en cuando a RN, te paso mi mail d@slushi.mx .... podremos hablar por hangouts si te parece bien solo me avisas cuando :D

**Comment by CesarLanderos** [comment]
Que bien que pudieron resolverlo!, si tienen iportunidad de hacer un PR para arreglarlo se los agradeceria bastante :).

En cuanto a lo que comentan de hacer este modulo sin cosigo nativo, pues si se puede, lo unico que no se puede hacer con solo javascript (y pues la razon principal por la que hice este modulo) es acceder al `deviceSessionId` o algo asi se llama, un token que openpay solicita para verificar que dispositivo hace la compra, por lo menos cuando yo lo hice no encontre nada para hacerlo con solo javascript, y las librerias que tiene openpay solo funcionan cuando se ejecuta en un navegador (hace uso del DOM para crear el id y esconderlo en un input) y pues react native todo lo hace con codigo nativo, no existe el DOM en react native.

Tengo mucho tiempo sin meterme a ver si ya actualizaron librerias o APIs los de openpay.

**Comment by Diego-Fu** [comment]
Hola! gracias por responder, 

el fix que comente creo que solo funciona en RN >= 47.0, sería cosa de probarlo.

Hace poco revise y creo que sigue usando el DOM, no se si hay otra forma de integrarlo en RN sin código nativo?

**Comment by CesarLanderos** [comment]
Esta bien, si es un breaking change pues movemos la version de esta libreria a 2.0.0, por eso no hay pex, y pues si no han actualizado eso del dom pues no, asi que, si quieres usar las utilidades antifraude de openpay pues se tiene que usar codigo nativo ¯\_(ツ)_/¯.

**Comment by Diego-Fu** [comment]
Hola! perdón por tardar tanto en responder, estuve investigando este cambio y ya deje un PR, tratare seguir aportando a esta librería, saludos! (:

**Comment by CesarLanderos** [comment]
closed in #3
