### ISSUE TITLE
Generación de token no se refleja en el dashboard

### ISSUE THREAD

**Issue by ghost** [CORBmx/react-native-openpay#5]
Estoy tratando de generar el token de la tarjeta y logro obtenerlo, pero este proceso no se refleja en la plataforma como se refleja desde la web. Al tratar de usarlo me dice que no es un id válido, entiendo que esto pasa por que no se refleja en el dashboard.

estoy usando la ID de aplicación y la llave pública, pero no se como obtiene el token de la tarjeta sin reflejarse en el dashboard.

**Comment by CesarLanderos** [comment]
pues la verdad no se porque no aparece en el dashboard, estamos usando este sdk para ios:

https://github.com/open-pay/openpay-ios

y para android:

https://github.com/open-pay/openpay-android

y en ninguno de los 2 veo algún parametro especial que tenga que ver con el dashboard, solo recibe los datos de la tarjeta, la genera y es todo.

si encuentras algo que pueda solucionarlo puedes postearlo aqui, o mejor aun!, hacer un PR 😄

**Comment by CesarLanderos** [comment]
Closing this because it has been inactive for 5 months, please reopen if the issue persists
