### ISSUE TITLE
Crashing on run-android

### ISSUE THREAD

**Issue by IamNotHuman** [CORBmx/react-native-openpay#6]
I am running RN: 0.42 and your version 1.0.6 but when I run-android to install on the phone it always crashes on 98% predexdebug

Error:

* What went wrong:
Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 2

**Comment by CesarLanderos** [comment]
hmmm, dont know why that is happening, has it ever worked? or is the first time that you install it?

**Comment by CesarLanderos** [comment]
Closing this because it has been inactive for 3 months, please reopen if the issue persists

**Comment by mikipdia** [comment]
It closes on Android 9, someone knows why it happens.
I'm react 59
