### ISSUE TITLE
Recompilar para soportar Android 64 bits

### ISSUE THREAD

**Issue by LuisGarcia9000** [CORBmx/react-native-openpay#8]
Al generar el apk se genera el siguiente error:

Execution failed for task ':react-native-openpay:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  error: resource android:style/TextAppearance.Material.Widget.Button.Borderless.Colored not found.
  error: resource android:style/TextAppearance.Material.Widget.Button.Colored not found.
  C:\tmp\cadi\react-native-openpay\intermediates\res\merged\release\values-v26\values-v26.xml:7: error: resource android:attr/colorError not found.
  C:\tmp\cadi\react-native-openpay\intermediates\res\merged\release\values-v26\values-v26.xml:11: error: resource android:attr/colorError not found.
  C:\tmp\cadi\react-native-openpay\intermediates\res\merged\release\values-v26\values-v26.xml:15: error: style attribute 'android:attr/keyboardNavigationClus

Esto es porque en mi app/build.gradle tengo:
   compileSdkVersion 28
    buildToolsVersion '28.0.3'

defaultConfig {
        minSdkVersion 16
        targetSdkVersion 28

Me desapareció el error al colocar los mismos parámetros en el build.gradle de este proyecto.

**Comment by CesarLanderos** [comment]
podrías crear un PR para agregar soporte a 64bits con la configuración apropiada por favor?
